quarkus.datasource.db-kind=oracle

quarkus.datasource.username=rm563343
quarkus.datasource.password=200906

quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl

quarkus.hibernate-orm.database.generation=update


quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with, origin
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS